###########################################################################
# Local Docker Registry Mirror
#
# Laurent Malvert <laurent.malvert@gmail.com>
# https://github.com/laurent-malvert/docker-registry-proxy-cache
###########################################################################

version: '3.3'


services:

  registry:
    restart: always
    image: registry:latest
    ports:
      - 5000:5000
    volumes:
      - ./config/default/config.yml:/etc/docker/registry/config.yml:ro
      - ./data/default:/var/lib/registry:rw

  registry-elastic:
    restart: always
    image: registry:latest
    ports:
      - 5001:5000
    volumes:
      - ./config/elastic/config.yml:/etc/docker/registry/config.yml:ro
      - ./data/elastic:/var/lib/registry:rw
