###########################################################################
# Local Docker Registry Mirror
#
# Laurent Malvert <laurent.malvert@gmail.com>
# https://github.com/laurent-malvert/docker-registry-proxy-cache
###########################################################################

version: '2.1'


services:

  registry:
    restart: always
    image: registry:latest
    ports:
      - 5000:5000
    volumes:
      - ./config:/etc/docker/registry:ro
      - ./data:/var/lib/registry:rw
